use anyhow::Context;

use crate::config::SynthesizerConfig;

/// Strip `<think>...</think>` blocks emitted by reasoning models (e.g. Nemotron, DeepSeek-R1).
/// Returns the text after the closing `</think>` tag, trimmed. If no such block is present,
/// returns the original string unchanged.
pub fn strip_thinking(content: &str) -> &str {
    let trimmed = content.trim_start();
    if trimmed.starts_with("<think>") {
        if let Some(end) = trimmed.find("</think>") {
            return trimmed[end + "</think>".len()..].trim_start();
        }
    }
    content
}

pub const DEFAULT_SYNTHESIS_PROMPT: &str = "\
You are a synthesis engine. You will receive multiple draft responses to a user's question, \
all generated by a fast but less accurate language model. Your task is to synthesize these \
drafts into a single, high-quality response.

Instructions:
- Extract what is correct and useful across all drafts
- Resolve contradictions by preferring the more specific or more accurate claim
- Fill in gaps where some drafts are incomplete but others are not
- Discard content that appears only once if it conflicts with the consensus
- Do not mention the drafts, the synthesis process, or that you are combining multiple responses
- Respond directly with the final answer as if you generated it yourself

The user's original question follows the draft responses.";

pub fn assemble_user_message(responses: &[String], original_prompt: &str) -> String {
    let n = responses.len();
    let mut msg = format!("Here are {n} draft responses to the user's question:\n");

    for (i, response) in responses.iter().enumerate() {
        msg.push_str(&format!("\n---\nDraft {}:\n{}\n", i + 1, response));
    }

    msg.push_str("\n---\nUser question:\n");
    msg.push_str(original_prompt);
    msg
}

pub async fn synthesize(
    client: &reqwest::Client,
    config: &SynthesizerConfig,
    responses: &[String],
    original_prompt: &str,
) -> anyhow::Result<String> {
    let system_prompt = config
        .system_prompt
        .as_deref()
        .unwrap_or(DEFAULT_SYNTHESIS_PROMPT);

    let user_msg = assemble_user_message(responses, original_prompt);

    let url = format!("{}/chat/completions", config.base_url);

    let mut body = serde_json::json!({
        "model": &config.model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": &user_msg}
        ]
    });

    if let Some(max_tokens) = config.max_tokens {
        body["max_tokens"] = serde_json::json!(max_tokens);
    }
    if let Some(temperature) = config.temperature {
        body["temperature"] = serde_json::json!(temperature);
    }

    let resp = client
        .post(&url)
        .header("Authorization", format!("Bearer {}", config.api_key))
        .header("Content-Type", "application/json")
        .json(&body)
        .send()
        .await
        .context("Synthesizer request failed")?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body_text = resp.text().await.unwrap_or_default();
        return Err(anyhow::anyhow!(
            "Synthesizer returned {status}: {body_text}"
        ));
    }

    let json: serde_json::Value = resp
        .json()
        .await
        .context("Failed to parse synthesizer response")?;

    let content = json["choices"][0]["message"]["content"]
        .as_str()
        .ok_or_else(|| anyhow::anyhow!("Synthesizer response missing choices[0].message.content"))?
        .to_string();

    Ok(strip_thinking(&content).to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_assemble_user_message_format() {
        let responses = vec![
            "First draft response".to_string(),
            "Second draft response".to_string(),
        ];
        let prompt = "What is the capital of France?";
        let result = assemble_user_message(&responses, prompt);

        assert!(result.contains("Here are 2 draft responses"), "missing count header");
        assert!(result.contains("Draft 1:"), "missing Draft 1 label");
        assert!(result.contains("Draft 2:"), "missing Draft 2 label");
        assert!(result.contains("User question:"), "missing User question label");
        assert!(result.contains(prompt), "missing original prompt");
        assert!(result.contains("First draft response"), "missing first response");
        assert!(result.contains("Second draft response"), "missing second response");
    }

    #[test]
    fn test_assemble_user_message_single() {
        let responses = vec!["Only draft".to_string()];
        let prompt = "Test prompt";
        let result = assemble_user_message(&responses, prompt);

        assert!(result.contains("Here are 1 draft responses"), "missing count header");
        assert!(result.contains("Draft 1:"), "missing Draft 1 label");
        assert!(!result.contains("Draft 2:"), "should not have Draft 2");
    }

    #[test]
    fn test_strip_thinking_removes_block() {
        let input = "<think>\nsome reasoning here\n</think>\nFinal answer.";
        assert_eq!(strip_thinking(input), "Final answer.");
    }

    #[test]
    fn test_strip_thinking_no_block() {
        let input = "Plain response with no think block.";
        assert_eq!(strip_thinking(input), input);
    }

    #[test]
    fn test_strip_thinking_leading_whitespace() {
        let input = "  <think>stuff</think>  Answer here.";
        assert_eq!(strip_thinking(input), "Answer here.");
    }

    #[test]
    fn test_default_prompt_contains_key_instructions() {
        assert!(
            DEFAULT_SYNTHESIS_PROMPT.contains("synthesis engine"),
            "missing 'synthesis engine'"
        );
        assert!(
            DEFAULT_SYNTHESIS_PROMPT.contains("Do not mention the drafts"),
            "missing 'Do not mention the drafts'"
        );
        assert!(
            DEFAULT_SYNTHESIS_PROMPT.contains("Respond directly with the final answer"),
            "missing 'Respond directly with the final answer'"
        );
    }

    #[test]
    fn test_system_prompt_override() {
        let config = SynthesizerConfig {
            base_url: "http://localhost:11434/v1".to_string(),
            api_key: "test".to_string(),
            model: "test-model".to_string(),
            max_tokens: None,
            temperature: None,
            system_prompt: Some("custom".to_string()),
        };
        assert_eq!(
            config.system_prompt.as_deref().unwrap_or(DEFAULT_SYNTHESIS_PROMPT),
            "custom"
        );
    }

    #[test]
    fn test_system_prompt_default() {
        let config = SynthesizerConfig {
            base_url: "http://localhost:11434/v1".to_string(),
            api_key: "test".to_string(),
            model: "test-model".to_string(),
            max_tokens: None,
            temperature: None,
            system_prompt: None,
        };
        assert_eq!(
            config.system_prompt.as_deref().unwrap_or(DEFAULT_SYNTHESIS_PROMPT),
            DEFAULT_SYNTHESIS_PROMPT
        );
    }
}
